<a href="https://colab.research.google.com/github/daimqureshi644/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy wit array

In [ ]:
import numpy as np
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


numpy with list

In [ ]:
y = [1,2,3,4]
print(y)

[1, 2, 3, 4]


In [ ]:
%timeit
[j**4 for j in range (1,9)]

[1, 16, 81, 256, 625, 1296, 2401, 4096]

In [ ]:
import numpy as np
%timeit np.arange(1,9)**4

1.98 µs ± 149 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Array


In [ ]:
import numpy as np
x = [1,2,3,4]
y = np.array([1,2,3,4,5])
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
l = []

for i in range(1,5):
  int_1 = input("Enter a num: ")
  l.append(int_1)

print(np.array(l))

Enter a num: 3
Enter a num: 7
Enter a num: 9
Enter a num: 767
['3' '7' '9' '767']


1 dimintional array

In [ ]:
import numpy as np
x = [1,2,3,4]
y = np.array([1,2,3,4,5])
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


2 diminisiol array

In [ ]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [ ]:
ar2 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(ar2)
print(ar2.ndim)

[[[1 2 3 4]
  [1 2 3 4]]]
3


In [ ]:
import numpy as np
x = [1,2,3,4]
y = np.array([1,2,3,4,5],ndin=10)
print(y)
print(type(y))
print(y.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
<class 'numpy.ndarray'>
10


Array using numpy function
zeros function

In [ ]:
import numpy as np
a_zero = np.zeros(4)
a_zero1 = np.zeros((3,4))

print(a_zero)
print()
print(a_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ones function

In [ ]:
import numpy as np
a_one = np.ones(4)
a_one1 = np.ones((3,4))

print(a_one)
print()
print(a_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


empty array function

In [ ]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


arange

In [ ]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


Dignoal

In [ ]:
ar_dia = np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


Line Space Function

In [ ]:
ar_lin = np.linspace(0,20,num= 5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


Random function **rand**

In [ ]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.50523483 0.06175805 0.99185726 0.19528446]


In [ ]:
var = np.random.rand(2,3)
print(var)

[[0.64734018 0.13191954 0.51305495]
 [0.46006538 0.99369675 0.31958015]]


**randn**

In [ ]:
var1 = np.random.randn(4)
print(var1)

[-0.0261385   1.58171948  0.11307672  0.3018673 ]


**ranf**

In [ ]:
var3 = np.random.ranf(4)
print(var3)

[0.04629125 0.77606494 0.5683128  0.63211549]


**RANDINT**

In [ ]:
var4 = np.random.randint(5,20,5)
print(var4)

[19 13  6 18  5]


Data type in numpy array

In [ ]:
import numpy as np
var = np.array([1,2,3,4])
print("Data Type:",var.dtype)

Data Type: int64


In [ ]:
import numpy as np
var = np.array([1.0,2.5,3.6,4.9])
print("Data Type:",var.dtype)

Data Type: float64


In [ ]:
import numpy as np
var = np.array(["a","b","c"])
print("Data Type:",var.dtype)

Data Type: <U3


In [ ]:
x = np.array([1,2,3,4],dtype= np.int8)
print("Data Type:",x.dtype)

Data Type: int8


In [ ]:
x1 = np.array([1,2,3,4],dtype= "f")
print("Data Type:",x1.dtype)
print(x1)

Data Type: float32
[1. 2. 3. 4.]


In [ ]:
x2 = np.array([1,2,3,4])

new = np.float128(x2)
new1 = np.int_(new)

print("Data Type:",x2.dtype)
print("Data Type:",new.dtype)
print("Data Type:",new1.dtype)
print(x1)
print(new)
print(new1)

Data Type: int64
Data Type: float128
Data Type: int64
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1 2 3 4]


In [ ]:
x3 = np.array([1,2,3,4])

new_1 = x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


Arithemtic operation

In [ ]:
import numpy as np

var = np.array([1,2,3,4,5])
varadd = var + 3
print(varadd)

[4 5 6 7 8]


In [ ]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([1,2,3,4,5])
varadd = var1 + var2
print(varadd)

[ 2  4  6  8 10]


In [ ]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([1,2,3,4,5])
varadd = var1 - var2
print(varadd)

[0 0 0 0 0]


In [ ]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([1,2,3,4,5])
varadd = var1 * var2
print(varadd)

[ 1  4  9 16 25]


In [ ]:
var = np.array([1,2,3,4,5])
varadd = var / 3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [ ]:
var = np.array([1,2,3,4,5])
varadd = var % 3
print(varadd)

[1 2 0 1 2]


In [ ]:
var1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
var2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(var1)
print()
print(var2)
print()
varadd = var1 + var2
print(varadd)

[[1 2 3 4 5]
 [1 2 3 4 5]]

[[1 2 3 4 5]
 [1 2 3 4 5]]

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [ ]:
var = np.array([1,2,3,4,5])
varadd = np.reciprocal(var)
print(varadd)

[1 0 0 0 0]


arithematic functions

In [ ]:
import numpy as np

var = np.array([1,2,3,4,5,6,7,5,3])
print("min: ",np.min(var),np.argmin(var))
print("max: ",np.max(var),np.argmin(var))
print("sqrt: ",np.sqrt(var),np.argmin(var))

min:  1 0
max:  7 0
sqrt:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.23606798 1.73205081] 0


In [ ]:
var1 = np.array([[1,3,5],[3,2,4]])
print(np.min(var1,axis= 1))

[1 2]


In [ ]:
var2 = np.array([1,3,4])
print(np.sin(var2))

[ 0.84147098  0.14112001 -0.7568025 ]


In [ ]:
var2 = np.array([1,3,4])
print(np.cumsum(var2))

[1 4 8]


**Shape**

In [ ]:
import numpy as np

var= np.array([[1,2,3,4],[1,2,3,4]])

print(var)
print()
print(var.shape)

In [ ]:
var1 = np.array([1,2,3,4], ndmin= 4)

print(var1)
print(var1.ndim)

[[[[1 2 3 4]]]]
4


**Reshape**

In [ ]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)

x = var2.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1
[[1 2]
 [3 4]
 [5 6]]
2


In [ ]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)

x1 = var3.reshape(2,3,2)
print(x1)
print(x1.ndim)

print()

one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


Broadcasting **bold text**

In [ ]:
import numpy as np

var1 =np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var3 = np.array([[1],[2],[3]])

print(var1+var2)

[2 4 6 8]


In [ ]:
var1 =np.array([1,2,3])
print(var1.shape)
print()
print(var1)
var2 = np.array([[1],[2],[3]])

print(var2.shape)
print()
print(var2)

print(var1+var2)

(3,)

[1 2 3]
(3, 1)

[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)

print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]


indexing & slicing

In [ ]:
import numpy as np

var = np.array([1,7,8,9])

print(var[2])
print(var[-3])

8
7


In [ ]:
var2 = np.array([[7,8,9],[5,6,7]])
print(var2)

print(var2.ndim)

print()
print(var2[0,1])

[[7 8 9]
 [5 6 7]]
2

8


In [ ]:
var2 = np.array([[[8,9],[6,7]]])
print(var2)

print(var2.ndim)

print()
print(var2[0,1,1])

[[[8 9]
  [6 7]]]
3

7


**slicing**

In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8])

print(x)
print()

print("2 to 5: ", x [1:4])
print(" 2 to end:", x [2:])
print(" start to 6:", x [:6])
print(" stop:", x [1:6:2])

[1 2 3 4 5 6 7 8]

2 to 5:  [2 3 4]
 2 to end: [3 4 5 6 7 8]
 start to 6: [1 2 3 4 5 6]
 stop: [2 4 6]


In [ ]:
var1 = np.array([[1,2,3,4,5],[4,5,6,7,8],[8,9,10,11,12]])

print(var1)
print()
print(var1[1,2:])

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 8  9 10 11 12]]

[6 7 8]


Iteration in numpy array

In [ ]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8])
print(var)
print()
for i in var:
  print(i)

[1 2 3 4 5 6 7 8]

1
2
3
4
5
6
7
8


In [ ]:
import numpy as np
var = np.array([[5,6,7,8],[1,2,3,4]])
print(var)
print()
for i in var:
  print(i)

for j in var:
  for l in j:
    print(l)

[[5 6 7 8]
 [1 2 3 4]]

[5 6 7 8]
[1 2 3 4]
5
6
7
8
1
2
3
4


In [ ]:
import numpy as np
var = np.array([[[5,6,7,8],[1,2,3,4]]])
print(var)
print(var.ndim)
print()
for i in var:
  for j in i:
    for k in j:
      print(k)

[[[5 6 7 8]
  [1 2 3 4]]]
3

5
6
7
8
1
2
3
4


In [ ]:
import numpy as np
var = np.array([[[5,6,7,8],[1,2,3,4]]])
print(var)
print(var.ndim)
print()

for i in np.nditer(var):
  print(i)

[[[5 6 7 8]
  [1 2 3 4]]]
3

5
6
7
8
1
2
3
4


In [ ]:
import numpy as np

# Example NumPy array
var = np.array([1, 2.5, 300])

for i in np.nditer(var, flags=["buffered"], op_dtypes=["S"]):
    print(i)

np.bytes_(b'1.0')
np.bytes_(b'2.5')
np.bytes_(b'300.0')


In [ ]:
import numpy as np
var = np.array([[[5,6,7,8],[1,2,3,4]]])
print(var)
print(var.ndim)
print()

for i,d in np.ndenumerate(var):
  print(i,d)

[[[5 6 7 8]
  [1 2 3 4]]]
3

(0, 0, 0) 5
(0, 0, 1) 6
(0, 0, 2) 7
(0, 0, 3) 8
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


COpy vs View

In [ ]:
import numpy as np
var = np.array([1,2,3,4])
co = var.copy()

var[1] = 40
print("var:",var)
print("copy: ",co)

var: [ 1 40  3  4]
copy:  [1 2 3 4]


In [ ]:
var = np.array([1,2,3,4])
vi = var.view()

var[1] = 60

print("var:",var)
print("view: ",vi)

var: [ 1 60  3  4]
view:  [ 1 60  3  4]


Join & Split in numpy array

In [ ]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([6,7,8,9])

ar = np.concatenate((var1,var2))

print(ar)

[1 2 3 4 6 7 8 9]


In [ ]:
var1 = np.array([[1,2],[3,4]])
var2 = np.array([[6,7],[8,9]])

ar = np.concatenate((var1,var2),axis= 1)

print(var1)
print()
print(var2)
print()
print(ar)

[[1 2]
 [3 4]]

[[6 7]
 [8 9]]

[[1 2 6 7]
 [3 4 8 9]]


In [ ]:
var1 = np.array([1,2,3,4])
var2 = np.array([6,7,8,9])

ar = np.stack((var1,var2),axis= 1)
ar_1 = np.hstack((var1,var2)) # row
ar_2 = np.vstack((var1,var2)) #coloum

print(ar)
print()
print(ar_1)
print()
print(ar_2)

[[1 6]
 [2 7]
 [3 8]
 [4 9]]

[1 2 3 4 6 7 8 9]

[[1 2 3 4]
 [6 7 8 9]]


In [ ]:
var = np.array([1,2,3,4,5,6,7,8])
print(var)

ar = np.array_split(var,3)
print()
print(ar)
print(type(ar))

[1 2 3 4 5 6 7 8]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
<class 'list'>


**Search**

In [ ]:
import numpy as np

var = np.array([1,2,3,3,2,4,5,6,7,2,8])

x = np.where(var == 2)
print(x)

(array([1, 4, 9]),)


In [ ]:
import numpy as np

var = np.array([1,2,3,3,2,4,5,6,7,2,8])

x = np.where((var%2) == 0)
print(x)

(array([ 1,  4,  5,  7,  9, 10]),)


In [ ]:
var = np.array([1,2,3,4,5,6,7])

x = np.searchsorted( var,[3,4,5], side = "right")
print(x)

[3 4 5]


**Sort**

In [ ]:
import numpy as np
var = np.array([1,2,32,4,52,6,7, 67])

print(np.sort(var))

[ 1  2  4  6  7 32 52 67]


In [ ]:
var = np.array(["a","k", "e","b"])

print(np.sort(var))

['a' 'b' 'e' 'k']


**filter** **array**

In [ ]:
var_1 = np.array(["a","k","e","b"])

f =[True,False,True,False]
new = var_1[f]

print(f)

[True, False, True, False]


**Shuffle**

In [ ]:
import numpy as np
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[1 5 3 4 2]


In [ ]:
import numpy as np
var = np.array([1,2,3,2,3,2,4,5])
x = np.unique(var, return_index= True)
print(x)

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 6, 7]))


In [ ]:
var = np.array([1,2,3,2,3,2,4,5,6])
x = np.resize(var,(2,3))
print(x)

[[1 2 3]
 [2 3 2]]


In [ ]:
var = np.array([1,2,3,2,3,2,4,5,6])
x = np.resize(var,(2,3))
print(x)
print("flatten : " ,x.flatten(order= "f"))
print("Ravel : " ,np.ravel(x))

[[1 2 3]
 [2 3 2]]
flatten :  [1 2 2 3 3 2]
Ravel :  [1 2 3 2 3 2]


**Insert**

In [ ]:
import numpy as np

var = np.array([1,2,3,4])
print(var)
v = np.insert(var, 2, 40)
print(v)

[1 2 3 4]
[ 1  2 40  3  4]


In [ ]:
var = np.array([[1,2,3],[1,2,3]])
print(var)
v = np.insert(var, 2, 40 ,axis= 1)
print(v)

[[1 2 3]
 [1 2 3]]
[[ 1  2 40  3]
 [ 1  2 40  3]]


**Delete**

In [ ]:
var = np.array([1,2,3,4])
print(var)
v = np.delete(var, 2)
print(v)

[1 2 3 4]
[1 2 4]


**Matrix in numpy Array**

In [ ]:
import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])
var1 = np.matrix([[1,2,3],[1,2,3]])
print(var)
print(type(var))
print()
print(var - var1)

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[0 0 0]
 [0 0 0]]


In [ ]:
var = np.array([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

var = np.matrix([[1,2],[1,2]])
var1 = np.matrix([[1,2],[1,2]])
print(var)
print(type(var))
print()
print(var - var1)
print()
print(var.dot(var1))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[0 0]
 [0 0]]

[[3 6]
 [3 6]]


In [ ]:
var = np.array([[1,2,3],[1,2,3]])
print(var)
print(type(var))
print()
print(np.transpose(var))
print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]


In [ ]:
var2 = np.array([[1,2],[1,2]])
print(var2)
print(type(var2))
print()
print(np.swapaxes(var2,0,1))
print(var2)

[[1 2]
 [1 2]]
<class 'numpy.ndarray'>

[[1 1]
 [2 2]]
[[1 2]
 [1 2]]


In [ ]:
import numpy as np

var2 = np.matrix([[1,2],[1,2]])
print(var2)
# Output:
# [[1 2]
#  [1 2]]

print()
print(np.linalg.matrix_power(var2,2))
print(np.linalg.matrix_power(var2,0))

[[1 2]
 [1 2]]

[[3 6]
 [3 6]]
[[1 0]
 [0 1]]


In [ ]:
var2 = np.matrix([[1,2],[1,2]])
print(var2)
# Output:
# [[1 2]
#  [1 2]]

print()
print(np.linalg.det(var2))

[[1 2]
 [1 2]]

0.0


**Merge**

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"a": [1,2,3,4], "b": [11,12,13,14]})
var2 = pd.DataFrame({"a": [1,2,3,5], "c": [21,22,23,24]})

pd.merge(var1,var2, how= "outer", indicator= True)

a     b     c      _merge
0  1  11.0  21.0        both
1  2  12.0  22.0        both
2  3  13.0  23.0        both
3  4  14.0   NaN   left_only
4  5   NaN  24.0  right_only

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"a": [1,2,3,4], "b": [11,12,13,14]})
var2 = pd.DataFrame({"a": [1,2,3,5], "b": [21,22,23,24]})

pd.merge(var1,var2, how= "outer", indicator= True,right_index= True , left_index= True,suffixes=("name","python"))

aname  bname  apython  bpython _merge
0      1     11        1       21   both
1      2     12        2       22   both
2      3     13        3       23   both
3      4     14        5       24   both

In [ ]:
var1 = pd.Series([1,2,3,4])
var2 = pd.Series([21,54,86,55])

pd.concat([var1,var2])

0     1
1     2
2     3
3     4
0    21
1    54
2    86
3    55
dtype: int64

In [ ]:
var1 = pd.DataFrame({"a": [1,2,3,4], "b": [11,12,13,14]})
var2 = pd.DataFrame({"a": [1,2,3,5], "b": [21,22,23,24]})
pd.concat([var1,var2], axis = 1)

a   b  a   b
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  14  5  24

In [ ]:
var1 = pd.DataFrame({"a": [1,2,3,4], "b": [11,12,13,14]})
var2 = pd.DataFrame({"a": [1,2,3,5], "b": [21,22,23,24]})
pd.concat([var1,var2], axis = 1, keys=("var1","var2"))

var1     var2    
     a   b    a   b
0    1  11    1  21
1    2  12    2  22
2    3  13    3  23
3    4  14    5  24

**Groupby**

In [ ]:
var1 = pd.DataFrame({"name": ["a","b","c","d","a","c","a","b","c","d","a"],
                     "s_1": [1,2,3,4,5,6,7,8,9,10,11],
                     "s_2": [1,2,3,4,5,6,7,8,9,10,11]})
var1

name  s_1  s_2
0     a    1    1
1     b    2    2
2     c    3    3
3     d    4    4
4     a    5    5
5     c    6    6
6     a    7    7
7     b    8    8
8     c    9    9
9     d   10   10
10    a   11   11

In [ ]:
var1 = pd.DataFrame({"name": ["a","b","c","d","a","c","a","b","c","d","a"],
                     "s_1": [1,2,3,4,5,6,7,8,9,10,11],
                     "s_2": [1,2,3,4,5,6,7,8,9,10,11]})

var_new = var1.groupby("name")
var_new

In [ ]:
var1 = pd.DataFrame({"name": ["a","b","c","d","a","c","a","b","c","d","a"],
                     "s_1": [1,2,3,4,5,6,7,8,9,10,11],
                     "s_2": [1,2,3,4,5,6,7,8,9,10,11]})

for x,y in var_new:
  print(x)
  print(y)

a
   name  s_1  s_2
0     a    1    1
4     a    5    5
6     a    7    7
10    a   11   11
b
  name  s_1  s_2
1    b    2    2
7    b    8    8
c
  name  s_1  s_2
2    c    3    3
5    c    6    6
8    c    9    9
d
  name  s_1  s_2
3    d    4    4
9    d   10   10


In [ ]:
var_new.min()

s_1  s_2
name          
a       1    1
b       2    2
c       3    3
d       4    4

In [ ]:
var_new.max()

s_1  s_2
name          
a      11   11
b       8    8
c       9    9
d      10   10

In [ ]:
var_new.mean()

s_1  s_2
name          
a     6.0  6.0
b     5.0  5.0
c     6.0  6.0
d     7.0  7.0

In [ ]:
li = list(var_new)
li

[('a',
     name  s_1  s_2
  0     a    1    1
  4     a    5    5
  6     a    7    7
  10    a   11   11),
 ('b',
    name  s_1  s_2
  1    b    2    2
  7    b    8    8),
 ('c',
    name  s_1  s_2
  2    c    3    3
  5    c    6    6
  8    c    9    9),
 ('d',
    name  s_1  s_2
  3    d    4    4
  9    d   10   10)]

**Join**

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"a": [1,2,3,4], "b": [11,12,13,14]})
var2 = pd.DataFrame({"c": [10,20,30,50], "d": [21,22,23,24]})

var1.join(var2)

a   b   c   d
0  1  11  10  21
1  2  12  20  22
2  3  13  30  23
3  4  14  50  24

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"a": [1,2,3,4], "b": [11,12,13,14]})
var2 = pd.DataFrame({"c": [10,20], "b": [21,22]})

result = pd.concat([var1, var2], ignore_index=True)
print(result)

     a   b     c
0  1.0  11   NaN
1  2.0  12   NaN
2  3.0  13   NaN
3  4.0  14   NaN
4  NaN  21  10.0
5  NaN  22  20.0


**Melt Function**

In [ ]:
import pandas as pd

var = pd.DataFrame({"days": [1,2,3,4,5,6], "eng": [10,12,14,12,13,12], "math": [12,15,18,19,15,14]})

var


days  eng  math
0     1   10    12
1     2   12    15
2     3   14    18
3     4   12    19
4     5   13    15
5     6   12    14

In [ ]:
pd.melt(var,id_vars =["days"])

days variable  value
0      1      eng     10
1      2      eng     12
2      3      eng     14
3      4      eng     12
4      5      eng     13
5      6      eng     12
6      1     math     12
7      2     math     15
8      3     math     18
9      4     math     19
10     5     math     15
11     6     math     14